name: webnma3-env
channels:
  - bioconda
  - salilab
  - conda-forge
  - defaults
dependencies:
  - attrs=21.2.0
  - biopython=1.78
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cycler=0.10.0
  - dssp=3.0.0
  - freetype=2.10.4
  - icu=58.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - iniconfig=1.1.1
  - jbig=2.1
  - jpeg=9d
  - kiwisolver=1.3.2
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libboost=1.67.0
  - libcblas=3.9.0
  - libcxx=12.0.1
  - libdeflate=1.7
  - libffi=3.4.2
  - libgcc=4.8.5
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - llvm-openmp=12.0.1
  - llvmlite=0.34.0
  - lz4-c=1.9.3
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - more-itertools=8.10.0
  - mustang=3.2.3
  - ncurses=6.2
  - numba=0.51.2
  - numpy=1.19.4
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.3
  - patsy=0.5.1
  - pillow=8.3.2
  - pip=21.2.4
  - pluggy=1.0.0
  - py=1.10.0
  - pyparsing=2.4.7
  - pytest=6.2.5
  - python=3.7.10
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2021.1
  - readline=8.1
  - scipy=1.5.3
  - seaborn=0.11.0
  - seaborn-base=0.11.0
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - typing_extensions=3.10.0.2
  - wheel=0.37.0
  - xz=5.2.5
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0
