name: webnma3-env
channels:
  - bioconda
  - salilab
  - conda-forge
  - defaults
dependencies:
  - biopython>=1.80
  - matplotlib=3.8.0
  - mustang=3.2.3
  - numba=0.57.1
  - numpy>=1.23.0
  - libzlib>=1.2.13
  - pytest=7.4.2
  - python>=3.10.0
  - scipy=1.11.3
  - seaborn=0.13.0