name: webnma3-env
channels:
  - bioconda
  - salilab
  - conda-forge
  - defaults
dependencies:
  - conda-forge:mamba
  - conda-forge:conda-libmamba-solver
  - biopython=1.78
  - dssp=3.0.0
  - matplotlib=3.3.3
  - mustang=3.2.3
  - numba=0.51.2
  - numpy=1.19.4
  - pytest=6.2.5
  - python=3.7.10
  - scipy=1.5.3
  - seaborn=0.11.0