package:
  name: webnma
  version: 3.5

source:
  git_rev: v3.5
  git_url: https://github.com/reuter-group/webnma3.git

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - mamba
    - conda-libmamba-solver
    - biopython >=1.81
    - dssp >=3.0
    - matplotlib
    - mustang >=3.2.3
    - numba >=0.57.1
    - numpy >=1.23
    - scipy
    - seaborn
    - python >=3.10

about:
  home: https://github.com/reuter-group/webnma3
  license: GPL-3.0
  license_file: LICENSE
  summary: Fast normal mode calculation and analyses for protein structures
