package:
  name: webnma
  version: 3.6

source:
  git_rev: v3.6
  git_url: https://github.com/reuter-group/webnma3.git

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - biopython=1.81
    - matplotlib=3.8.0
    - mustang=3.2.3
    - numba=0.57.1
    - numpy=1.23.0
    - scipy=1.11.3
    - seaborn=0.13.0
    - libzlib=1.2.13
    - python=3.11.6

about:
  home: https://github.com/reuter-group/webnma3
  license: GPL-3.0
  license_file: LICENSE
  summary: Fast normal mode calculation and analyses for protein structures
