package:
  name: webnma
  version: 3.6

source:
  git_rev: v3.6
  git_url: https://github.com/reuter-group/webnma3.git

requirements:
  host:
    - python
    - setuptools
  build:
    - python=3.11.6
  run:
    - conda-libmamba-solver >=23.1.0
    - numpy >=1.23.0
    - mustang
    - biopython
    - matplotlib
    - numba
    - scipy
    - seaborn
    - libzlib
    - python >=3.11.6

about:
  home: https://github.com/reuter-group/webnma3
  license: GPL-3.0
  license_file: LICENSE
  summary: Fast normal mode calculation and analyses for protein structures
