name: Python Package using Conda

on: 
  workflow_dispatch:
    branches:
      - main

jobs:
  build-macos-linux:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ macos-latest , ubuntu-latest ]   
        python-version: ['3.11.6']
    steps:
    - uses: actions/checkout@v4
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        sudo chown -R 501:20 $CONDA
        conda install python=${{ matrix.python-version }}
        conda install anaconda-client conda-build 
        conda install -n base conda-libmamba-solver
        conda config --set solver libmamba
    - name: Build and Publish Conda
      run: |
        conda build conda-recipe/ -c bioconda -c salilab --user ddx --token  ${{ secrets.ANACONDA_TOKEN }}

